# Generated by Django 3.1.6 on 2021-07-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('fullname', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=500)),
                ('phone', models.IntegerField(default=0)),
                ('cnic', models.IntegerField(default=0)),
                ('Delivery', models.CharField(max_length=500)),
                ('list', models.CharField(default='', max_length=200)),
                ('payment', models.CharField(max_length=500)),
            ],
        ),
    ]
