# Generated by Django 3.1.6 on 2021-09-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('deliver_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=500)),
                ('phone', models.IntegerField(default=0)),
                ('cnic', models.IntegerField(default=0)),
                ('city', models.CharField(default='', max_length=200)),
                ('user', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=8)),
            ],
        ),
    ]
