# Generated by Django 3.1.6 on 2021-09-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_deliver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
