# Generated by Django 3.1.6 on 2021-09-16 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210916_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='deliverd_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 0, 15, 19, 917049), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 0, 15, 19, 917049), null=True),
        ),
    ]
