# Generated by Django 4.0.2 on 2022-03-04 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210916_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete',
            name='deliverd_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 40, 30, 429881), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cnic',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 16, 40, 30, 429881), null=True),
        ),
    ]
