# Generated by Django 4.0.2 on 2022-03-06 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_complete_deliverd_time_alter_order_cnic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='received_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complete',
            name='deliverd_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 13, 30, 7, 481889), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 13, 30, 7, 479895), null=True),
        ),
    ]
