# Generated by Django 4.0.2 on 2022-03-06 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_complete_received_money_alter_complete_deliverd_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliver',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='complete',
            name='deliverd_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 16, 24, 9, 729504), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 6, 16, 24, 9, 729504), null=True),
        ),
    ]
