# Generated by Django 4.0.2 on 2022-04-15 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_complete_deliverd_time_alter_order_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complete',
            name='deliver_cnic',
        ),
        migrations.AddField(
            model_name='complete',
            name='branch_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='complete',
            name='deliverd_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 20, 41, 2, 699512), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 20, 41, 2, 699512), null=True),
        ),
    ]
