# Generated by Django 4.0.2 on 2022-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=50)),
                ('rent_price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='asc/media')),
            ],
        ),
    ]
