# Generated by Django 4.0.2 on 2022-03-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='TYPE',
            field=models.CharField(choices=[('Vehicle', 'Vehicle'), ('Tool', 'Tool'), ('Drone', 'Drone')], default='Vehicle', max_length=50, null=True),
        ),
    ]
