# Generated by Django 4.0.2 on 2022-03-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_name', models.CharField(max_length=50)),
                ('TYPE', models.CharField(choices=[('Vehicle', 'Vehicle'), ('Tool', 'Tool'), ('Drone', 'Drone')], default='Drone', max_length=50, null=True)),
                ('rent_price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='asc/media')),
            ],
        ),
    ]
