# Generated by Django 4.0.2 on 2022-03-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_drone'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('cnic', models.IntegerField(default=0)),
                ('branch', models.CharField(max_length=50)),
                ('booking_date', models.DateField()),
            ],
        ),
    ]
