# Generated by Django 4.0.2 on 2022-03-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_remove_booking_booking_date_booking_booking_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
