# Generated by Django 4.0.2 on 2022-03-23 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='drone_name',
            new_name='v_name',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='tool_name',
            new_name='v_name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_name',
            new_name='v_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 20, 9, 30, 467759), null=True),
        ),
    ]
