# Generated by Django 4.0.2 on 2022-03-23 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_rename_drone_name_drone_v_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='v_name',
            new_name='tool_name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 21, 6, 45, 616065), null=True),
        ),
    ]
