# Generated by Django 4.0.2 on 2022-03-24 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_rename_v_name_drone_drone_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='branche',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=500)),
                ('office_timing', models.CharField(default='', max_length=500)),
                ('branch_tele', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 21, 12, 51, 114597), null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 21, 12, 51, 114597), null=True),
        ),
    ]
