# Generated by Django 4.0.2 on 2022-04-15 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_alter_booking_booking_time_alter_branche_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 21, 6, 50, 273705), null=True),
        ),
        migrations.AlterField(
            model_name='branche',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 21, 6, 50, 273705), null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 21, 6, 50, 273705), null=True),
        ),
    ]
