# Generated by Django 4.0.4 on 2022-06-29 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_alter_booking_booking_time_alter_branche_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=20)),
                ('mesage', models.CharField(default='', max_length=1000)),
                ('contact_time', models.DateTimeField(default=datetime.datetime(2022, 6, 29, 22, 36, 43, 542387), null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 22, 36, 43, 540388), null=True),
        ),
        migrations.AlterField(
            model_name='branche',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 22, 36, 43, 541389), null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 22, 36, 43, 541389), null=True),
        ),
    ]
